name = "IsopycnalSurfaces"
uuid = "29a8b8bc-eb2a-4ada-9a47-be49547c4d59"
authors = ["G Jake Gebbie"]
version = "0.1.5"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Dierckx = "0.5"
Interpolations = "0.12,0.13"
julia = "1.6,1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
